### ISSUE TITLE
Implement a basic todo list which is persisted in local storage

### ISSUE THREAD

**Issue by kevinmchan** [openwell-app/openwell#1]
Features:
- [ ] Add new todo list items
- [ ] Display open todo items
- [ ] Mark todo item as complete
- [ ] Display completed todo items
- [ ] Delete todo list item
- [ ] Edit todo list item
